### ISSUE TITLE
Unable to apply false color mapping

### ISSUE THREAD

**Issue by chetbis** [cornerstonejs/cornerstoneWADOImageLoader#197] opened 2018-04-29 07:07 UTC
Hi, I am unable to apply false color mapping when I use wadoimageloader. I did like this as what is there in [https://rawgit.com/cornerstonejs/cornerstone/master/example/falseColorMapping/index.html](url)
`
  var colormap = cornerstone.colors.getColormap(selectedMap.id),
        viewport = cornerstone.getViewport(dicomMount);
  viewport.colormap = colormap;
  cornerstone.setViewport(dicomMount, viewport);
  cornerstone.updateImage(dicomMount, true);             
`
is there anyway I can fix this?

**Comment by khadakeb** [comment] 2018-07-11 05:07
@chetbis I am also facing same issue. Is there fix for this?

**Comment by chetbis** [comment] 2018-07-11 06:29
@khadakeb unable to find anything.

**Comment by swederik** [comment] 2018-07-11 07:01
Sorry for the delay.

I have seen this recently and it is definitely an issue. The problem is that the image loader is setting image.render and Cornerstone is just blindly following it because it exists. I think we may want to remove the image.render property in favour of letting Cornerstone decide how to render it.

See 
https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/createImage.js#L147

**Comment by swederik** [comment] 2018-07-11 07:11
Could you test the version from the PR to verify this fixes your problem? Thanks

**Comment by khadakeb** [comment] 2018-07-11 08:29
@swederik  I have tested PR and it fixed my issue. Thanks.

**Comment by swederik** [comment] 2018-07-11 08:45
Great! Thanks!

**Closed** 2019-03-27 01:19 UTC
Labels: :bug: Bug: Report
