### ISSUE TITLE
"Cannot set property 'pixelData' of undefined..." - error in Angular project build with --prod parameter

### ISSUE THREAD

**Issue by Anduil** [cornerstonejs/cornerstoneWADOImageLoader#233] opened 2018-11-26 10:10 UTC
I get that error if i build my Angular7 project with --prod parameter.
![photo_2018-11-26_13-00-43](https://user-images.githubusercontent.com/20019775/49007094-abc6bd00-f17b-11e8-87a0-f8e867ac57a4.jpg)

This error is here:
![screenshot_24](https://user-images.githubusercontent.com/20019775/49007193-f21c1c00-f17b-11e8-9bab-dcac9323c7e7.png)

To solve it problem I've changed the package settings of the node_module: 
![image](https://user-images.githubusercontent.com/20019775/49007308-34ddf400-f17c-11e8-9952-969e019dd3cc.png)

So, I've did it not the **"min"** and it work for now. But such solution, as i think, not correct. So, I've made description of my issue here.

**Comment by dannyrb** [comment] 2019-03-27 00:56
👋 Hello @Anduil, unfortunately, I am unable to reproduce. If you are able to provide a minimal reproduction, it would go a long way toward helping me resolve your issue.

As this issue is a bit older, I'm going to close it for now, but I'm more than happy to reopen it if/when a reproduction surfaces.

**Closed by dannyrb** 2019-03-27 00:56 UTC
Labels: :bug: Bug: Report, Awaiting Reproduction

**Comment by Hariprasathkin** [comment] 2021-07-23 10:47
I'm getting same issue angular 10. what is actual solution for this?

**Comment by andresjz** [comment] 2021-10-02 03:31
As @Anduil  mentioned this issue only happens when you build you app in prod mode, otherwise the app seems working fine, apparently the `*min.js` version have some missing function that cause the bug at the end
